version: "3.7"

services:
  vote:
    # This build context/dockerfile definition is only required because this way 
    # "docker-compose build" can be directly run inside the solution folder.
    build:
      context: ../src/vote
      dockerfile: $PWD/vote/Dockerfile
    image: vote-webapp:1.0
    restart: on-failure
    ports:
      - "5000:8080"
    networks:
      - front-tier
      - back-tier
    cap_drop:
      - ALL
    cap_add:
      - CAP_CHOWN
      - SETUID
      - SETGID

  result:
    # This build context/dockerfile definition is only required because this way 
    # "docker-compose build" can be directly run inside the solution folder.
    build:
      context: ../src/result
      dockerfile: $PWD/result/Dockerfile
    image: result-webapp:1.0
    restart: on-failure
    depends_on:
      - "db"
    ports:
      - "5001:8080"
    networks:
      - front-tier
      - back-tier

  worker:
    # This build context/dockerfile definition is only required because this way 
    # "docker-compose build" can be directly run inside the solution folder.
    build:
      context: ../src/worker
      dockerfile: $PWD/worker/Dockerfile
    image: worker-app:1.0
    restart: on-failure
    depends_on:
      - "redis"
    networks:
      - back-tier

  redis:
    image: redis:5.0.5-alpine
    container_name: redis
    restart: on-failure
    networks:
      - back-tier

  db:
    image: postgres:11.4-alpine
    container_name: db
    restart: on-failure
    volumes:
      - "./db-data:/var/lib/postgresql/data"
    networks:
      - back-tier

networks:
  front-tier:
  back-tier:
    internal: true
